### ISSUE TITLE
Telescope pointing from first event may be badly mistaken

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#1293] opened 2024-09-18 14:47 UTC
https://github.com/cta-observatory/cta-lstchain/blob/e4a5b7a36dfd643acf47b9006f51fe882b6dbc5c/lstchain/high_level/hdu_table.py#L270-L272

@juanjq  has seen some instance of the telescope pointing (RA,dec) for the first event in a DL2 file being quite off from the true pointing for (most of) the run. Example: run 17821. This is the only pointing stored in the DL3 file for the whole run, as RA_PNT, DEC_PNT

We think this has consequences for the ring background model: the model for such runs is badly mistaken, probably because symmetry is assumed around a wrong sky position.

**Comment by morcuended** [comment] 2024-09-18 15:31
Are these pointing coordinates from the first event internally used in Gammapy for ring background calculation? Or is it whatever coordinates you define? What pointing information do you suggest including the HDU table?

**Comment by maxnoe** [comment] 2024-09-18 16:58
@moralejo Do you understand why this happens? Is the timestamp wrong or the interpolation or the drive log?

**Comment by juanjq** [comment] 2024-09-19 04:47
In principle it seems that gammapy assumes symmetry around pointing, that is written in the DL3 and it does not need to be input. And @maxnoe I don't know 100%, but I don't think the issue is related to the dragon timestamps, we think this happens because sometimes when wobbling, LST can oscillate in the first instants of a run, resulting in a error of few 0.1 deg approx, then stabilizes. (Or this is what it seems looking the specific set of runs I'm working with: 17820-17825, in most of them a small oscillation in pointing can be seen at the start of the run) So then taking the first pointing as general is not that accurate. So I don't know which option can be better but the mean position can be taken, or maybe excluding start and end of the run, I guess there is not a unique solution for that.

**Comment by SeiyaNozaki** [comment] 2024-09-19 08:51
I asked Armand before and it seems this is a real feature. You can also see this mispointing at the beginning of each tracking in the drive log. I had similar issues for source-dep analysis (fixed in #1211), so I agree with the suggestion by @juanjq (not take pointing info excluding the start of run)
https://www.lst1.iac.es/operations/drive/Log_cmd.2024-06-15.html

**Comment by morcuended** [comment] 2024-09-19 09:05
Indeed when checking the center of off regions in Gammapy we can see this dispersion. Agree as well with @juanjq proposal of excluding the start/end and then taking the average

**Comment by maxnoe** [comment] 2024-09-19 10:15
Ok, so the issue is not that the pointing is *wrong* for those events, it is that it is not yet stable on the wanted position and only wrong to use it as the one pointing position for the DL3 file.

Maybe we should identify the time range of this unstable pointing and exclude it via the GTI.

**Comment by maxnoe** [comment] 2024-10-03 19:48
We (@juanjq and me) just had a look into the pointing of one of the runs, and it is very clear that it is not-yet-stable pointing from the drive in the first ~35 seconds of the run:

![pointing_run_17821](https://github.com/user-attachments/assets/82d18f8e-30a2-4d4f-8d80-6f0203fde50a)

So for the fix, I would propose:

* Compute the mean pointing starting from something like 60s, maybe with an exceptional case for runs that are shorted.
* Identify the start of stable pointing by looking at e.g. by the RMSE from this mean pointing.
* Exclude the "unstable" part in the GTI of the DL3 files.

**Comment by moralejo** [comment] 2024-10-07 08:55
Apologies for long silence on this. Completely excluding the unstable part is risky, we may e.g. miss some relevant GRB data  - which can be properly reconstructed because we do have the event-wise reconstructed coordinates (and also event-wise pointing, although this is currently available in DL2, not in DL3). 

Why is the pointing not included event-wise in DL3? Although in general we will track a RA-dec sky position, there will also be occasional "drift scans". And if one has full-enclosure IRFs it should be possible to analyze all data together despite the changing pointing.  Can we simply add more entries in the pnt_table (see below) and then gammapy will do some interpolation for each event when needed?  https://github.com/cta-observatory/cta-lstchain/blob/e4a5b7a36dfd643acf47b9006f51fe882b6dbc5c/lstchain/high_level/hdu_table.py#L417

Order-0 solution however is indeed writing the "correct value" and excluding  periods which deviate significantly. As usual with this sort of thing, the hard part is to decide on reasonable cut values, deal with exceptions, etc.

**Comment by morcuended** [comment] 2024-10-07 09:10
The pointing is included event-wise in the DL3 files, isn't it?

![snapshot DL3 file](https://github.com/user-attachments/assets/d704dd1d-4d89-4ab5-ae8c-44852b626bf5)

**Comment by moralejo** [comment] 2024-10-07 09:12
> The pointing is included event-wise in the DL3 files, isn't it?
> 
> ![snapshot DL3 file](https://private-user-images.githubusercontent.com/32680689/374105417-d704dd1d-4d89-4ab5-ae8c-44852b626bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTI1OTYsIm5iZiI6MTcyODI5MjI5NiwicGF0aCI6Ii8zMjY4MDY4OS8zNzQxMDU0MTctZDcwNGRkMWQtNGQ4OS00YWI1LWFlOGMtNDQ4NTJiNjI2YmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA5MTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTVkMGNlMzdmMTEwNzQyYTE5NTA2MGIyN2E0ZDA1ZmY0NjcwMzlmNWQ3ZGU3MjUzMTFhNjZkNzU4YjdhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jKaSmHsztV24JMJpjTds-jn4lx27I2bMk_sWQ4ubHGM)

Those are reconstructed RA, dec, right?

**Comment by morcuended** [comment] 2024-10-07 09:14
> Those are reconstructed RA, dec, right?

Yes

**Comment by moralejo** [comment] 2024-10-07 09:37
> > Those are reconstructed RA, dec, right?
> 
> Yes

So, not the **telescope** pointing. I am not sure I am following, sorry...

**Comment by maxnoe** [comment] 2024-10-07 09:50
GADF has the mechanism of string the monitoring pointing table, however nothing that it is preliminary and not implemented in science tools:
https://gamma-astro-data-formats.readthedocs.io/en/v0.3/events/pointing.html

And indeed, Gammapy does not support it:
https://github.com/gammapy/gammapy/issues/4860

The simple solution for a high priority alert would be to cut the observations into multiple files that can have a constant ra/dec pointing and analyze them together.

**Comment by morcuended** [comment] 2024-10-07 11:02
> So, not the telescope pointing. I am not sure I am following, sorry...

My bad, it was me not following it. Disregard my comment.

**Comment by maxnoe** [comment] 2024-10-07 12:14
> Why is the pointing not included event-wise in DL3? Although in general we will track a RA-dec sky position, there will also be occasional "drift scans". 

Just for completeness, this is supported by a fixed pointing in alt AZ with obsmode drift.

The only thing that is currently not supported is pointing not stable in either icrs or altaz.

**Comment by moralejo** [comment] 2024-10-07 14:39
> > Why is the pointing not included event-wise in DL3? Although in general we will track a RA-dec sky position, there will also be occasional "drift scans".
> 
> Just for completeness, this is supported by a fixed pointing in alt AZ with obsmode drift.

Ah, ok, thanks! I guess we also have to update our DL2 to DL3 tool to allow setting obs_mode to drift upon request.

**Comment by morcuended** [comment] 2024-10-07 16:12
> Ah, ok, thanks! I guess we also have to update our DL2 to DL3 tool to allow setting obs_mode to drift upon request.

I've just created a new issue #1301 to remember this point

**Comment by moralejo** [comment] 2024-10-08 07:42
@SeiyaNozaki I do  not understand the fix you mentioned for source-dependent analysis. 
With the current code, I think the problematic runs will have wrong expected_src_x, y, computed with the first event's pointing :
https://github.com/cta-observatory/cta-lstchain/blob/620d0a90d9c30b872b049bbfe283d66f934799d3/lstchain/high_level/hdu_table.py#L324-L325

I am not sure though what that is used for (since we have the src-dep parameters already computed at DL1/DL2 level with the event-wise pointing)

**Comment by moralejo** [comment] 2024-10-08 08:18
Opened PR: #1302

**Closed** 2024-10-30 14:30 UTC
